### ISSUE TITLE
64 Bit Support

### ISSUE THREAD

**Issue by tkambler** [eGood/CardReaderPlugin#3]
This plugin doesn't seem to support 64 bit architecture - is that right? Beginning February 1, new / updated app store apps must include support for 64 bit architecture:

http://cordova.apache.org/announcements/2014/11/25/ios-64bit.html

**Comment by AlexGamezo** [comment]
Thank you for the info. I'm looking into it now and will update when I have dealt with the issue.

**Comment by tkambler** [comment]
:+1:

**Comment by AlexGamezo** [comment]
Are you having any specific errors regarding building for 64bit that you're not getting while building 32bit version? It'd be helpful in tracking down the issue, as I've not had any issues yet.

**Comment by tkambler** [comment]
[Here is the output](https://dl.dropboxusercontent.com/u/832215/cordova-64.txt) from `cordova compile ios`:

**Comment by tkambler** [comment]
@AlexGamezo My apologies. Upon further review, I believe I was mistaken here. The problem lies not with a lack of support for 64-bit archs (arm), but instead of x86 architecture at all. I was able to work around this issue by compiling *specifically* to the device with:

```
$ cordova compile --device
```
