### ISSUE TITLE
Encrypted APN (Credit Card Number)

### ISSUE THREAD

**Issue by jackrr** [eGood/CardReaderPlugin#4]
The plugin is working well, but I'm getting an encrypted credit card number from the scan. I would like to grab the credit card number as seen on the front of the card. The MagTek documentation seems to imply that the encryption level is configurable:

http://www.magtek.com/documentation/public/99875582-1.03.pdf

Is it possible to configure the plugin so that it doesn't encrypt the card number? My objective-C isn't very good, though, am I misunderstanding the doc?

**Comment by theinventor** [comment]
That is configuration done in the reader, my understanding is when you buy a reader it comes with an encryption key for the gateway you are using, OR, comes unencrypted - and it isn’t something you can adjust.

When we buy USB swipers its the same way, we have some unencrypted ones - but I’ve only seen mobile readers come with encryption on them

**Comment by bcgood** [comment]
Troy,

You're correct, the card readers you get comes encrypted to the gateway
you're using and isn't something you can adjust.

On Fri, Jun 12, 2015 at 10:48 AM, Troy Anderson <notifications@github.com>
wrote:

> That is configuration done in the reader, my understanding is when you buy
> a reader it comes with an encryption key for the gateway you are using, OR,
> comes unencrypted - and it isn’t something you can adjust.
>
> When we buy USB swipers its the same way, we have some unencrypted ones -
> but I’ve only seen mobile readers come with encryption on them
>
>
>
> > On Jun 12, 2015, at 10:40 AM, Jack Ratner <notifications@github.com>
> wrote:
> >
> > I
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eGood/CardReaderPlugin/issues/4#issuecomment-111572488>
> .
>



-- 
*Brian Chioy | *Developer

*eGood *|  Ordinary Actions, Extraordinary Change

(321) 252-8390 *or* Find me on Google Hangouts
eGood.com <http://www.egood.com/>  |  brian@egood.com

#ChooseGood
#ShareJoy

© 2015 eGood, Inc.
