### ISSUE TITLE
Does this Plugin workss

### ISSUE THREAD

**Issue by nanduahmed** [eGood/CardReaderPlugin#5]
Just wanted to integrate thsi plugin here. Do you have any documentation available for this ?

**Comment by bcgood** [comment]
Sorry @nanduahmed there isn't one at the moment, but it is plug and play pretty simple to understand. By the way, this only works for regular MagTek readers and is separate from PayPal Here readers

**Comment by nanduahmed** [comment]
Thanks @bcgood for the info.
