### ISSUE TITLE
Call to jQuery in "isDeviceConnected"

### ISSUE THREAD

**Issue by Ludusamo** [eGood/CardReaderPlugin#6]
JQuery is not added as a dependency by default. A JQuery call is made within **isDeviceConnected** for debugging purposes on lines 10 and 17 in **magtek_udynamo.js**. I suggest that this call is taken out or documentation on JQuery being a dependency for this plugin is made.

**Comment by AlexGamezo** [comment]
Valid point. Removing jQuery parts of the call, as the debugging can be performed through available callbacks
