### ISSUE TITLE
Integration with Payment Gateway (e.g. Srtipe)

### ISSUE THREAD

**Issue by AshleyDeng** [eGood/CardReaderPlugin#9]
Hi,

There is not too much info or documentation on this plugin. Based on what I have read, we are able to get the encrypted credit card number from the reader #4 . 

With this encrypted data, can we make a payment request through payment gateways (e.g. Stripe)? If yes, what's the Stripe API for this?

Thanks!
Ashley

**Comment by AlexGamezo** [comment]
If Stripe API supports working with MagTek encrypted devices, then yes. Last I checked, that wasn't the case. There are a handful of gateways that work with it, WorldPay being one of them
